apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: dockerwebcontainer
        #image: pankajsingh23/dockerweb
        image: target2021.azurecr.io/dockerweb:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  type: LoadBalancer 
  selector:
    app: web
  ports: 
    - port: 80    
      protocol: TCP
      targetPort: 80
