apiVersion: apps/v1
kind: Deployment
metadata:
  name: apideployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: dockerapicontainer
        #image: pankajsingh23/dockerapi
        image: target2021.azurecr.io/dockerapi:#{Build.BuildId}#
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  #name: apiservice
  name: dockerapicontainer
spec:
  type: LoadBalancer
  selector:
    app: api
  ports: 
    - port: 80
      protocol: TCP
      targetPort: 80