apiVersion: v1
kind: Secret
metadata:
  name: azuresecrets
type: opaque
data:
  appconfigconnectionstring: base64encodedconnectionstring
  AZURE_CLIENT_SECRET: base64encodedAzureClientSecret  
# stringData:
  # ENVIRONMENT_TYPE: DEV
  # ConfigFromLocal: false
  # ASPNETCORE_ENVIRONMENT: Development
  # AZURE_CLIENT_ID: 3f5f12f4-bc2c-45ba-b62e-330309a38621
  # AZURE_TENANT_ID: d52c9ea1-7c21-47b1-82a3-33a74b1f74b8